name: CI
on:
  push:
  pull_request:
    branches: ["main"]
  workflow_dispatch: 
  
jobs:
   build:
     runs-on: ubuntu-latest
     steps: 
       - uses: actions/checkout@v3
       - name: Greet user
         run: echo welcome to actions 
   test:
     runs-on: ubuntu-latest
     steps: 
       - uses: actions/checkout@v3
       - name: Greet user
         run: echo welcome to test
   deploy:
     runs-on: ubuntu-latest
     steps: 
       - uses: actions/checkout@v3
       - name: Greet user
         run: echo welcome to deploy
